name: Update Homebrew Formula

on:
  repository_dispatch:
    types: [formula-update]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update formula from template
        run: |
          # Extract data from the dispatch payload
          VERSION="${{ github.event.client_payload.release.version }}"
          DARWIN_ARM64_SHA="${{ github.event.client_payload.checksums.darwin_arm64 }}"
          DARWIN_X86_64_SHA="${{ github.event.client_payload.checksums.darwin_x86_64 }}"
          LINUX_X86_64_SHA="${{ github.event.client_payload.checksums.linux_x86_64 }}"
          
          # Remove 'v' prefix if present
          CLEAN_VERSION="${VERSION#v}"
          
          echo "Updating formula to version: $CLEAN_VERSION"
          echo "Darwin ARM64 SHA: $DARWIN_ARM64_SHA"
          echo "Darwin x86_64 SHA: $DARWIN_X86_64_SHA"
          echo "Linux x86_64 SHA: $LINUX_X86_64_SHA"
          
          # Generate the formula from template
          cp Formula/awd-cli.rb.template Formula/awd-cli.rb
          
          # Replace template placeholders with actual values
          sed -i "s/{{VERSION}}/$CLEAN_VERSION/g" Formula/awd-cli.rb
          sed -i "s/{{DARWIN_ARM64_SHA}}/$DARWIN_ARM64_SHA/g" Formula/awd-cli.rb
          sed -i "s/{{DARWIN_X86_64_SHA}}/$DARWIN_X86_64_SHA/g" Formula/awd-cli.rb
          sed -i "s/{{LINUX_X86_64_SHA}}/$LINUX_X86_64_SHA/g" Formula/awd-cli.rb
          
          echo "✅ Formula updated successfully"

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/awd-cli.rb
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update AWD CLI to v${{ github.event.client_payload.release.version }}"
            git push
            echo "✅ Formula update pushed to tap repository"
          fi
