name: Update Formula

on:
  repository_dispatch:
    types: [formula-update]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update formula with new version and checksums
        run: |
          CLEAN_VERSION="${{ github.event.client_payload.release.version }}"
          # Remove 'v' prefix if present
          CLEAN_VERSION="${CLEAN_VERSION#v}"
          
          FORMULA_FILE="Formula/awd-cli.rb"
          
          echo "Updating Homebrew formula for version $CLEAN_VERSION..."
          echo "Darwin ARM64 SHA: ${{ github.event.client_payload.checksums.darwin_arm64 }}"
          echo "Darwin x86_64 SHA: ${{ github.event.client_payload.checksums.darwin_x86_64 }}"
          echo "Linux x86_64 SHA: ${{ github.event.client_payload.checksums.linux_x86_64 }}"
          
          # Update the formula file
          sed -i.bak \
            -e "s/version \".*\"/version \"$CLEAN_VERSION\"/" \
            -e "s/PLACEHOLDER_ARM64_SHA/${{ github.event.client_payload.checksums.darwin_arm64 }}/" \
            -e "s/PLACEHOLDER_X86_64_SHA/${{ github.event.client_payload.checksums.darwin_x86_64 }}/" \
            -e "s/PLACEHOLDER_LINUX_SHA/${{ github.event.client_payload.checksums.linux_x86_64 }}/" \
            "$FORMULA_FILE"
          
          # Remove backup file
          rm "${FORMULA_FILE}.bak"
          
          echo "✅ Formula updated successfully!"
      
      - name: Commit and push formula update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/awd-cli.rb
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update formula for ${{ github.event.client_payload.release.version }}"
            git push
            echo "✅ Formula update pushed to tap repository"
          fi
